#!/bin/bash

function checkwork {
	
	code=$?

	if [ $# -ne 1 ];
	then
		echo "Нужно передаеть один аргумент!"
		exit 1
	fi

	if [ $code -ne 0 ];
	then
		echo -e "\e[0;31mЧто-то пошло не так на этапе $1!\e[0m"
		exit 1
	else
		echo -e "\e[0;32mЭтап $1 прошел успешно!\n\e[0m"
	fi	
}

path_to_dir=~/projectVPN/clientconf

echo -e "\e[0;34mЭтап 1/10. Генерация сертификатов и ключей для пользователя $1.\e[0m"
mkdir -p ~/clients/keys && \
	cd ~/easy-rsa && \
	./easyrsa --batch gen-req $1 nopass && \
	cp pki/private/$1.key ~/clients/keys/ && \
	./easyrsa --batch sign-req client $1 && \
	cp ~/easy-rsa/ta.key ~/clients/keys/ && \
	sudo cp /etc/openvpn/server/ca.crt ~/clients/keys/
	mkdir -p ~/clients/files && \
	cp $path_to_dir/base.conf  ~/clients/ && \
	cp $path_to_dir/make_config.sh ~/clients/ $$ \
	chmod 700 ~/clients/make_config.sh
	sudo chown -r $USER:$USER ~/clients/*
checkwork 1

