#!/bin/bash

function checkwork {
	
	code=$?

	if [ $# -ne 1 ];
	then
		echo "Нужно передаеть один аргумент!"
		exit 1
	fi

	if [ $code -ne 0 ];
	then
		echo -e "\e[0;31mЧто-то пошло не так на этапе $1!\e[0m"
		exit 1
	else
		echo -e "\e[0;32mЭтап $1 прошел успешно!\n\e[0m"
	fi	
}

path_to_easy_rsa_dir=~/projectVPN/clientconf

echo -e "\e[0;34mЭтап 1/10. Генерация сертификатов и ключей для пользователя $1.\e[0m"
mkdir -p ~/clients/keys && \
	cd ~/easy-rsa && \
	./easyrsa --batch gen-req $1 nopass && \
	cp pki/private/$1.key ~/clients/keys/ && \
	./easyrsa --batch sign-req client $1 && \
	cp ~/easy-rsa/ta.key ~/clients/keys/ && \
	sudo cp /etc/openvpn/server/ca.crt ~/clients/keys/
	sudo chown $USER:$USER ~/clients/keys/*
	mkdir -p ~/clients/files && \
	cp $path_to_easy_rsa_dir/base.conf
checkwork 1

echo -e "\e[0;34mЭтап 2/10. Конфигарция клиента $1.\e[0m"
mkdir -p ~/clients/files && \

checkwork 2


#echo -e "\e[0;34mЭтап 3/10. Копирвоание конфиграции клиента.\e[0m"
#cp $path_to_easy_rsa_dir/vars .
#checkwork 3

echo -e "\e[0;34mЭтап 4/5. Создание запроса на сертификат и ключа для сервера.\e[0m"
./easyrsa --batch gen-req server nopass
checkwork 4

echo -e "\e[0;34mЭтап 5/10. Подпись сертификата удостоверяющим центром.
Здесь потребуется ввести пароль, заданный при генерации корневого сертефиката СA.\e[0m"
./easyrsa --batch sign-req server server
checkwork 5

echo -e "\e[0;34mЭтап 6/10 Генерация tls-ключа для дополнительной безопасности.\e[0m"
openvpn --genkey --secret ta.key
checkwork 6

echo -e "\e[0;34mЭтап 7/10. Копирование необходимых файлов в /etc/openvpn/server.\e[0m"
sudo cp ./pki/private/server.key /etc/openvpn/server && \
	sudo cp ./pki/ca.crt /etc/openvpn/server/ && \
	sudo cp ./pki/issued/server.crt /etc/openvpn/server/ && \
	sudo cp ./ta.key /etc/openvpn/server/
checkwork 7

echo -e "\e[0;34mЭтап 8/10 Настройка openVPN и маршрутизации.\e[0m"
sudo cp $path_to_easy_rsa_dir/server.conf /etc/openvpn/server && \
	sudo sed -i 's/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/' /etc/sysctl.conf && \
	sudo sysctl -p
checkwork 8

echo -e "\e[0;34mЭтап 9/10 Запуск openVPN.\e[0m"
sudo systemctl -f enable openvpn-server@server.service && \
	sudo systemctl start openvpn-server@server.service 
checkwork 9
