#!/bin/bash

function checkwork {
	
	if [ $# -ne 1 ];
	then
		echo "Нужно передаеть один аргумент!"
		exit 1
	fi

	if [ $? -ne 0 ];
	then
		echo -e "\e[0;31mЧто-то пошло не так на этапе $1!\e[0m"
		exit 1
	else
		echo -e "\e[0;32mЭтап $1 прошел успешно!\n\e[0m"
	fi	
}
path_to_easy_rsa_dir="~/projectVPN/easy-rsa"

echo -e "\e[0;34mЭтап 1/4. Скачивание программ\e[0m"
sudo apt-get update -y > /dev/null && sudo apt-get install easy-rsa -y > /dev/null
checkwork 1

echo -e "\e[0;34mЭтап 2/4. Настройка easy-rsa\e[0m"
mkdir ~/easy-rsa && ln -s /usr/share/easy-rsa/* ~/easy-rsa/ > /dev/null && cd ~/easy-rsa  && ./easyrsa init-pki
checkwork 2

echo -e "\e[0;34mЭтап 3/4. Копирвоание конфиграции.\e[0m"
echo "Этап 3/4. Копирвоание конфиграции."
cp $path_to_easy_rsa_dir/vars .
checkwork 3

echo -e "\e[0;34mЭтап 4/4. Создание CA.\nЗдесь вам предложат ввести кодовую фразу, которую впоследствии нужно
вводить для получения доступа к вашему СA при совершении операций с cертификатами.\e[0m"
./easyrsa --batch build-ca
checkwork 4
